//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 *                 
 * 			
 * 
 * <p>Java class for Channel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Channel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="channelType" type="{http://eform.e-gov.bg/dictionary/Code}Code"/>
 *         &lt;element name="openingHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processTime" type="{http://eform.e-gov.bg/dictionary/ProcessTime}ProcessTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="contactAddressCountry" type="{http://eform.e-gov.bg/dictionary/Code}Code" minOccurs="0"/>
 *         &lt;element name="contactAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Channel", namespace = "http://eform.e-gov.bg/dictionary/Channel", propOrder = {
    "identifier",
    "channelType",
    "openingHours",
    "processTime",
    "contactAddressCountry",
    "contactAddress"
})
public class Channel {

    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected Code channelType;
    protected String openingHours;
    protected List<ProcessTime> processTime;
    protected Code contactAddressCountry;
    protected String contactAddress;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the channelType property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getChannelType() {
        return channelType;
    }

    /**
     * Sets the value of the channelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setChannelType(Code value) {
        this.channelType = value;
    }

    /**
     * Gets the value of the openingHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpeningHours() {
        return openingHours;
    }

    /**
     * Sets the value of the openingHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpeningHours(String value) {
        this.openingHours = value;
    }

    /**
     * Gets the value of the processTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessTime }
     * 
     * 
     */
    public List<ProcessTime> getProcessTime() {
        if (processTime == null) {
            processTime = new ArrayList<ProcessTime>();
        }
        return this.processTime;
    }

    /**
     * Gets the value of the contactAddressCountry property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getContactAddressCountry() {
        return contactAddressCountry;
    }

    /**
     * Sets the value of the contactAddressCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setContactAddressCountry(Code value) {
        this.contactAddressCountry = value;
    }

    /**
     * Gets the value of the contactAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * Sets the value of the contactAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress(String value) {
        this.contactAddress = value;
    }

}
