//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 			
 * 
 * <p>Java class for LegalEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegalEntity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="legalData" type="{http://eform.e-gov.bg/dictionary/LegalEntity}LegalData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegalEntity", namespace = "http://eform.e-gov.bg/dictionary/LegalEntity", propOrder = {
    "legalData"
})
public class LegalEntity {

    protected LegalData legalData;

    /**
     * Gets the value of the legalData property.
     * 
     * @return
     *     possible object is
     *     {@link LegalData }
     *     
     */
    public LegalData getLegalData() {
        return legalData;
    }

    /**
     * Sets the value of the legalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalData }
     *     
     */
    public void setLegalData(LegalData value) {
        this.legalData = value;
    }

}
