//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 			
 * 
 * <p>Java class for Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Location">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="country" type="{http://eform.e-gov.bg/dictionary/Code}Code"/>
 *         &lt;element name="address" type="{http://eform.e-gov.bg/dictionary/Location}Address" minOccurs="0"/>
 *         &lt;element name="regix" type="{http://eform.e-gov.bg/dictionary/RegixSync}RegixSync" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Location", namespace = "http://eform.e-gov.bg/dictionary/Location", propOrder = {
    "country",
    "address",
    "regix"
})
public class Location {

    @XmlElement(required = true)
    protected Code country;
    protected Address address;
    protected RegixSync regix;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setCountry(Code value) {
        this.country = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the regix property.
     * 
     * @return
     *     possible object is
     *     {@link RegixSync }
     *     
     */
    public RegixSync getRegix() {
        return regix;
    }

    /**
     * Sets the value of the regix property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegixSync }
     *     
     */
    public void setRegix(RegixSync value) {
        this.regix = value;
    }

}
