//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.egov.eforms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.egov.eforms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link PublicService }
     * 
     */
    public PublicService createPublicService() {
        return new PublicService();
    }

    /**
     * Create an instance of {@link PublicOrganization }
     * 
     */
    public PublicOrganization createPublicOrganization() {
        return new PublicOrganization();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link ProcessTime }
     * 
     */
    public ProcessTime createProcessTime() {
        return new ProcessTime();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link RequestAuthor }
     * 
     */
    public RequestAuthor createRequestAuthor() {
        return new RequestAuthor();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link LegalData }
     * 
     */
    public LegalData createLegalData() {
        return new LegalData();
    }

    /**
     * Create an instance of {@link LegalEntity }
     * 
     */
    public LegalEntity createLegalEntity() {
        return new LegalEntity();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link RegixSync }
     * 
     */
    public RegixSync createRegixSync() {
        return new RegixSync();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link PersonalData }
     * 
     */
    public PersonalData createPersonalData() {
        return new PersonalData();
    }

    /**
     * Create an instance of {@link Jurisdiction }
     * 
     */
    public Jurisdiction createJurisdiction() {
        return new Jurisdiction();
    }

    /**
     * Create an instance of {@link IdentificationDocument }
     * 
     */
    public IdentificationDocument createIdentificationDocument() {
        return new IdentificationDocument();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link AuthorizationDocument }
     * 
     */
    public AuthorizationDocument createAuthorizationDocument() {
        return new AuthorizationDocument();
    }

    /**
     * Create an instance of {@link CommunicationChannels }
     * 
     */
    public CommunicationChannels createCommunicationChannels() {
        return new CommunicationChannels();
    }

    /**
     * Create an instance of {@link ContactPoint }
     * 
     */
    public ContactPoint createContactPoint() {
        return new ContactPoint();
    }

    /**
     * Create an instance of {@link ImageObject }
     * 
     */
    public ImageObject createImageObject() {
        return new ImageObject();
    }

    /**
     * Create an instance of {@link ImageObjectContent }
     * 
     */
    public ImageObjectContent createImageObjectContent() {
        return new ImageObjectContent();
    }

    /**
     * Create an instance of {@link Evidence }
     * 
     */
    public Evidence createEvidence() {
        return new Evidence();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

}
