//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://eform.e-gov.bg/dictionary/ImageObject")
package com.ib.urireg.eforms;
