//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 		
 * 			
 * 
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personalData" type="{http://eform.e-gov.bg/dictionary/PersonalData}PersonalData" minOccurs="0"/>
 *         &lt;element name="identificationDocument" type="{http://eform.e-gov.bg/dictionary/IdentificationDocument}IdentificationDocument" minOccurs="0"/>
 *         &lt;element name="permanentAddress" type="{http://eform.e-gov.bg/dictionary/Location}Location" minOccurs="0"/>
 *         &lt;element name="presentAddress" type="{http://eform.e-gov.bg/dictionary/Location}Location" minOccurs="0"/>
 *         &lt;element name="corrAddress" type="{http://eform.e-gov.bg/dictionary/Location}Location" minOccurs="0"/>
 *         &lt;element name="representation" type="{http://eform.e-gov.bg/dictionary/Representation}Representation" minOccurs="0"/>
 *         &lt;element name="authorizationDocument" type="{http://eform.e-gov.bg/dictionary/AuthorizationDocument}AuthorizationDocument" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", namespace = "http://eform.e-gov.bg/dictionary/Person", propOrder = {
    "personalData",
    "identificationDocument",
    "permanentAddress",
    "presentAddress",
    "corrAddress",
    "representation",
    "authorizationDocument"
})
public class Person {

    protected PersonalData personalData;
    protected IdentificationDocument identificationDocument;
    protected Location permanentAddress;
    protected Location presentAddress;
    protected Location corrAddress;
    protected Representation representation;
    protected AuthorizationDocument authorizationDocument;

    /**
     * Gets the value of the personalData property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalData }
     *     
     */
    public PersonalData getPersonalData() {
        return personalData;
    }

    /**
     * Sets the value of the personalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalData }
     *     
     */
    public void setPersonalData(PersonalData value) {
        this.personalData = value;
    }

    /**
     * Gets the value of the identificationDocument property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationDocument }
     *     
     */
    public IdentificationDocument getIdentificationDocument() {
        return identificationDocument;
    }

    /**
     * Sets the value of the identificationDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationDocument }
     *     
     */
    public void setIdentificationDocument(IdentificationDocument value) {
        this.identificationDocument = value;
    }

    /**
     * Gets the value of the permanentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * Sets the value of the permanentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setPermanentAddress(Location value) {
        this.permanentAddress = value;
    }

    /**
     * Gets the value of the presentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getPresentAddress() {
        return presentAddress;
    }

    /**
     * Sets the value of the presentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setPresentAddress(Location value) {
        this.presentAddress = value;
    }

    /**
     * Gets the value of the corrAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getCorrAddress() {
        return corrAddress;
    }

    /**
     * Sets the value of the corrAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setCorrAddress(Location value) {
        this.corrAddress = value;
    }

    /**
     * Gets the value of the representation property.
     * 
     * @return
     *     possible object is
     *     {@link Representation }
     *     
     */
    public Representation getRepresentation() {
        return representation;
    }

    /**
     * Sets the value of the representation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Representation }
     *     
     */
    public void setRepresentation(Representation value) {
        this.representation = value;
    }

    /**
     * Gets the value of the authorizationDocument property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationDocument }
     *     
     */
    public AuthorizationDocument getAuthorizationDocument() {
        return authorizationDocument;
    }

    /**
     * Sets the value of the authorizationDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationDocument }
     *     
     */
    public void setAuthorizationDocument(AuthorizationDocument value) {
        this.authorizationDocument = value;
    }

}
