//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 *                
 * 			
 * 
 * <p>Java class for PublicOrganization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicOrganization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="legalIdentifier" type="{http://eform.e-gov.bg/dictionary/Identifier}Identifier"/>
 *         &lt;element name="identifier" type="{http://eform.e-gov.bg/dictionary/Identifier}Identifier" maxOccurs="unbounded"/>
 *         &lt;element name="preferredLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alternativeLabel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spatial" type="{http://eform.e-gov.bg/dictionary/Location}Location" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="organizationType" type="{http://eform.e-gov.bg/dictionary/Code}Code" minOccurs="0"/>
 *         &lt;element name="homepage" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="logo" type="{http://eform.e-gov.bg/dictionary/ImageObject}ImageObject" minOccurs="0"/>
 *         &lt;element name="subOrganizations" type="{http://eform.e-gov.bg/dictionary/PublicOrganization}PublicOrganization" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="administrativeUnits" type="{http://eform.e-gov.bg/dictionary/PublicOrganization}PublicOrganization" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="contactPoint" type="{http://eform.e-gov.bg/dictionary/ContactPoint}ContactPoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{http://eform.e-gov.bg/dictionary/Location}Location" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="activeFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="activeTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicOrganization", namespace = "http://eform.e-gov.bg/dictionary/PublicOrganization", propOrder = {
    "legalIdentifier",
    "identifier",
    "preferredLabel",
    "alternativeLabel",
    "description",
    "spatial",
    "organizationType",
    "homepage",
    "logo",
    "subOrganizations",
    "administrativeUnits",
    "contactPoint",
    "address",
    "activeFrom",
    "activeTo"
})
public class PublicOrganization {

    @XmlElement(required = true)
    protected Identifier legalIdentifier;
    @XmlElement(required = true)
    protected List<Identifier> identifier;
    @XmlElement(required = true)
    protected String preferredLabel;
    protected List<String> alternativeLabel;
    protected String description;
    protected List<Location> spatial;
    protected Code organizationType;
    @XmlSchemaType(name = "anyURI")
    protected String homepage;
    protected ImageObject logo;
    protected List<PublicOrganization> subOrganizations;
    protected List<PublicOrganization> administrativeUnits;
    protected List<ContactPoint> contactPoint;
    protected List<Location> address;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activeFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activeTo;

    /**
     * Gets the value of the legalIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getLegalIdentifier() {
        return legalIdentifier;
    }

    /**
     * Sets the value of the legalIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setLegalIdentifier(Identifier value) {
        this.legalIdentifier = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the preferredLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredLabel() {
        return preferredLabel;
    }

    /**
     * Sets the value of the preferredLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredLabel(String value) {
        this.preferredLabel = value;
    }

    /**
     * Gets the value of the alternativeLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativeLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativeLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAlternativeLabel() {
        if (alternativeLabel == null) {
            alternativeLabel = new ArrayList<String>();
        }
        return this.alternativeLabel;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the spatial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpatial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Location }
     * 
     * 
     */
    public List<Location> getSpatial() {
        if (spatial == null) {
            spatial = new ArrayList<Location>();
        }
        return this.spatial;
    }

    /**
     * Gets the value of the organizationType property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getOrganizationType() {
        return organizationType;
    }

    /**
     * Sets the value of the organizationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setOrganizationType(Code value) {
        this.organizationType = value;
    }

    /**
     * Gets the value of the homepage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * Sets the value of the homepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomepage(String value) {
        this.homepage = value;
    }

    /**
     * Gets the value of the logo property.
     * 
     * @return
     *     possible object is
     *     {@link ImageObject }
     *     
     */
    public ImageObject getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageObject }
     *     
     */
    public void setLogo(ImageObject value) {
        this.logo = value;
    }

    /**
     * Gets the value of the subOrganizations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subOrganizations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubOrganizations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicOrganization }
     * 
     * 
     */
    public List<PublicOrganization> getSubOrganizations() {
        if (subOrganizations == null) {
            subOrganizations = new ArrayList<PublicOrganization>();
        }
        return this.subOrganizations;
    }

    /**
     * Gets the value of the administrativeUnits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the administrativeUnits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdministrativeUnits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicOrganization }
     * 
     * 
     */
    public List<PublicOrganization> getAdministrativeUnits() {
        if (administrativeUnits == null) {
            administrativeUnits = new ArrayList<PublicOrganization>();
        }
        return this.administrativeUnits;
    }

    /**
     * Gets the value of the contactPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactPoint }
     * 
     * 
     */
    public List<ContactPoint> getContactPoint() {
        if (contactPoint == null) {
            contactPoint = new ArrayList<ContactPoint>();
        }
        return this.contactPoint;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Location }
     * 
     * 
     */
    public List<Location> getAddress() {
        if (address == null) {
            address = new ArrayList<Location>();
        }
        return this.address;
    }

    /**
     * Gets the value of the activeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActiveFrom() {
        return activeFrom;
    }

    /**
     * Sets the value of the activeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActiveFrom(XMLGregorianCalendar value) {
        this.activeFrom = value;
    }

    /**
     * Gets the value of the activeTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActiveTo() {
        return activeTo;
    }

    /**
     * Sets the value of the activeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActiveTo(XMLGregorianCalendar value) {
        this.activeTo = value;
    }

}
