//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.28 at 02:42:59 PM EEST 
//


package com.ib.urireg.eforms;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *              
 * 			
 * 
 * <p>Java class for RequestAuthor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestAuthor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" type="{http://eform.e-gov.bg/dictionary/Person}Person" minOccurs="0"/>
 *         &lt;element name="communicationChannels" type="{http://eform.e-gov.bg/dictionary/CommunicationChannels}CommunicationChannels" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestAuthor", namespace = "http://eform.e-gov.bg/dictionary/RequestAuthor", propOrder = {
    "person",
    "communicationChannels"
})
public class RequestAuthor {

    protected Person person;
    protected CommunicationChannels communicationChannels;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the communicationChannels property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationChannels }
     *     
     */
    public CommunicationChannels getCommunicationChannels() {
        return communicationChannels;
    }

    /**
     * Sets the value of the communicationChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationChannels }
     *     
     */
    public void setCommunicationChannels(CommunicationChannels value) {
        this.communicationChannels = value;
    }

}
