urireg.src.version=1.7

system.model.id=${system.model.id}

# REGIX - kogato testvame localno vseki moje da si smeni patq pri nego kadeto e slojil sertifikata, da ne se ka4va razkomentirano.
#regix.wsdl.url=https://service-regix-test.egov.bg/RegiXEntryPointV2.svc.singlewsdl.xml
#regix.keystore.location=D:/certs/regix.indexbg.p12
#regix.keystore.password=XXXXXX
